gesdinet_jwt_refresh_token:
    ttl: 28800 # Temps de vie du refresh token en secondes (8h ici)
    ttl_update: true
    user_provider: app_user_provider  
    manager_type: orm 
    refresh_token_class: App\Entity\RefreshToken 

